### PR TITLE
fix: switches underdotter and underdot arround

### PR DESCRIPTION
**Pull request by ulisses-cruz**
This made the 'darkplus' theme stop working for me.
It is a tiny fix.

### CODE REVIEW

**Comment by gutyina70** [comment]
What's your neovim version?
If you are using a release (latest is v0.7.2), then it should be underdot.
But if you use a non-released, development version (after [this PR](https://github.com/neovim/neovim/pull/19159) got merged) then it should be underdotted.
I assume you have an outdated development build, please update if this is the case.

**Comment by ulisses-cruz** [comment]
image

**Comment by gutyina70** [comment]
You have a development build, but it doesn't show the exact version (due to compiler flags), we don't know which is the last commit for your build, but it's behind the commit that changed underdot to underdotted. Also version with a commit looks like this:
nvim-version

Older 0.8.0 builds only speak underdot and new ones underdotted. As far as I know it is not possible to check the commit version using `vim.fn.has`.

Your best choice is to use another version. Either downgrade to stable 0.7.2, or upgrade to the latest development build.

**Comment by gutyina70** [comment]
You can use a protected call to try setting the highlight with underdotted, and if that fails fall back to the old underdot, this way we don't need to check version at all:
```lua
  local underdotted_ok, _ = pcall(hl, 0, "markdownUrl", { fg = c.cyan, bg = 'NONE', underdotted=true })
  if not underdotted_ok then
    hl(0, "markdownUrl", { fg = c.cyan, bg = 'NONE', underdot=true, })
  end
```

But I still recommend keeping your neovim updated especially when using a development build.

**Comment by ulisses-cruz** [comment]
Thanks @gutyina70. I've reinstalled neovim, and it works fine for me now.
You can close the pull request if you want.

**Comment by gutyina70** [comment]
I'm glad it's working for you @ulisses-cruz!
I would say this issue is uncommon and should not be fixed by this repo instead the user should update.
Can you please close this PR? I don't have permission to do it.

**Pull request closed without merging**
