### PR TITLE
added diagnostic hl's to be consistent

### PR DESCRIPTION
**Pull request by lewpoly**
Noticed the diagnostic colors in NvimTree were different from every other highlight. This PR fixes that.

### CODE REVIEW

**Review by gutyina70 — CHANGES_REQUESTED** [review]
Make indentation consistent with the rest of the file (use 2 tabs instead of 4 spaces).

**Comment by lewpoly** [comment]
Sorry, didn't notice until you said something. Fixed.

**Comment by gutyina70** [comment]
This is now fixed by https://github.com/LunarVim/darkplus.nvim/commit/699594055893c506da12838e9f2f5ecd84a471b4#diff-f6396e3ad2299402e37c1ffe426fc126f7c6bfc3ef40b49eed8ed657447a1442R273-R277.

**Comment by lewpoly** [comment]
Scheme was rewritten.

**Pull request closed without merging**
